### ISSUE TITLE
Loading the fiddle failed: Not Found

### ISSUE THREAD

**Issue by dnicolson** [electron/electronjs.org-new#146]
Most of the "Open in Fiddle" buttons open links that result in a "Loading the fiddle failed: Not Found" error in Electron Fiddle.

Here is an example of a link that doesn't work:
https://www.electronjs.org/docs/v14-x-y/tutorial/represented-file

This link works:
https://www.electronjs.org/docs/latest/tutorial/examples

It looks a workaround is to replace `v14-x-y` with `latest` in the URL.

Electron Fiddle 0.26.0 (12.0.14)
macOS 11.6 (20G165)

**Comment by erickzhao** [comment]
@dnicolson The problem here is with the URL formatting for the "Open in Fiddle" link. I've moved the repo accordingly.
