### ISSUE TITLE
spacing between search bar and language button

### ISSUE THREAD

**Issue by khareyash05** [electron/electronjs.org-new#195]
There is less spacing between the search bar and the language when on mobile version. I would like to work on it
![image](https://user-images.githubusercontent.com/60147732/159109441-9faee5e4-8c99-4d87-ba35-4768ad971022.png)

**Comment by molant** [comment]
Thanks, you are assigned!

**Comment by molant** [comment]
Actually, the screenshot you took is from "the old website". The homage is still in that infrastructure and we don't plan to do any work in there.

The new homepage is being developed by @erickzhao in this [Pull Request](https://github.com/electron/electronjs.org-new/pull/187) and [its preview](https://electronjsorg-new-pr-187.herokuapp.com/).

I'll close this issue as it is out-of-scope, but if you see any problems in that PR please let us know!
