### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by tawanda-profuse** [electron/electronjs.org-new#204]
I was reading the README.md file inside the [electron/electronjs.org-new](https://github.com/electron/electronjs.org-new) repository and came across a dysfunctional link.

Under the How to Add a New Blogpost heading, there is a broken link to the [Docusaurus](https://docusaurus.io/docs/2.0.0-beta.0/blog#adding-posts) website.

For your reference: _"To add a new blogpost you need to create a new markdown file under /blog. The supported frontmatter options are the ones documented in [Docusaurus](https://docusaurus.io/docs/2.0.0-beta.0/blog#adding-posts)."_

**Comment by molant** [comment]
Fixed via #205 
Thanks @tawanda-profuse
