### ISSUE TITLE
[bug] translate docs, Cannot be translated in Chinese

### ISSUE THREAD

**Issue by steady-join** [electron/electronjs.org-new#206]
![image](https://user-images.githubusercontent.com/29935583/162403604-db41c862-66dd-4492-b21a-a139dc357823.png)

**Comment by molant** [comment]
I don't see that console error, but the website isn't translated even when accessing directly https://www.electronjs.org/zh/docs/latest/

I've downloaded the latest translation from Crowdin and it looks OK. Maybe a problem with the build step and Docusaurus not finding `zh` and defaulting to `en` @erickzhao ?
