### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by albu77** [electron/electronjs.org-new#235]
Just have the following ![image](https://user-images.githubusercontent.com/624802/180611492-1963c86c-8aef-4095-9dea-0fc36350671d.png) and can't understand the meaning of the answer

**Comment by molant** [comment]
Hi @albu77,

My priorities have changed quite a lot over the last few months and I haven't had the time to review any translations. I thought that someone was taking care of this, but it looks like it hasn't been the case. I'm deeply sorry about that.

I have one or two ideas on how we could do better. If you are still interested, would you mind joining us during the next ecosystem meeting?
It will be on Wednesday 27th at 9am PT.

Thanks for your patience and bringing this up (again) 🙏

**Comment by albu77** [comment]
Issue closed since I'm now proofreading
