### ISSUE TITLE
[Feature Request]: Make this interactive with hover

### ISSUE THREAD

**Issue by PritamSarbajna** [electron/electronjs.org-new#241]
### Problem Description

I just think if you make this section little more interactive

![Screenshot (179)](https://user-images.githubusercontent.com/90236635/182138676-d116e974-32ac-4686-b89b-038a846d1c36.png)
 

### Proposed Solution

I'd like to add when hovering it changes color or transform like a card I can change this can you assign it to me ?

### Alternatives Considered

You can also add a slideshow or decorate but I don't recommend

**Comment by erickzhao** [comment]
That's part of the old website and not in this codebase. You can clone the repo and run `yarn start` to see the updated homepage that hasn't shipped yet.
