### ISSUE TITLE
[BUG] translation not working

### ISSUE THREAD

**Issue by BlackHole1** [electron/electronjs.org-new#250]
This is an upstream bug

Ref: https://github.com/crowdin/crowdin-cli/issues/467

**Comment by erickzhao** [comment]
Seems like this could be fixed with some infra upgrades according to https://github.com/crowdin/crowdin-cli/issues/467#issuecomment-1223961485. Thanks for bringing this up!

> jDeploy 3+ uses zulu as the default provider, and the CI script indicates that crowdin uses jDeploy 3.2.0 for current builds.
It is likely that this bug was produced by an old version of crowdin which uses an older version of jDeploy.
