### ISSUE TITLE
Website translations displaying English

### ISSUE THREAD

**Issue by albu77** [electron/electronjs.org-new#252]
The web site is not reactive to some language selection. It was already same trouble some days ago......
I'm working on the french translation and can't verify it on the website

**Comment by erickzhao** [comment]
Related https://github.com/electron/electronjs.org-new/issues/255

**Comment by erickzhao** [comment]
@albu77 I believe the build started failing because of a misformed tag in the translation.

![image](https://user-images.githubusercontent.com/16010076/186777592-28d23b92-1a48-408d-b8bd-6dc64e2d4f67.png)

**Comment by albu77** [comment]
Ok, I was looking for an error  in my last translations (because Actually I don't have have access yet to the errors). But I didn't think to go back to this one.  Thanks
