### ISSUE TITLE
[BUG]: The showcase page display is incorrect

### ISSUE THREAD

**Issue by BlackHole1** [electron/electronjs.org-new#261]
Link: https://www.electronjs.org/apps/

### Expected Behavior

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/8198408/190545308-8951426a-8ea2-4baf-915d-efd65ea676f1.png">

### Actual Behavior

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/8198408/190545457-3bbc05db-7af2-4d8a-91cc-3f02a68131f2.png">

**Comment by kirtanchandak** [comment]
I am not getting what exactly we have to change ?

**Comment by BlackHole1** [comment]
> I am not getting what exactly we have to change ?

<img width="868" alt="image" src="https://user-images.githubusercontent.com/8198408/190846458-933d59cf-c96d-4e73-8db8-89f279998b6f.png">

**Comment by KrishJ999** [comment]
Hey can you please assign me the issue. I can fix it.

**Comment by erickzhao** [comment]
@KrishJ999 PRs always welcome

**Comment by KrishJ999** [comment]
Hey @erickzhao from my understanding of the codebase, I think changes are required in the url of the logos in [Your Repo](https://github.com/erickzhao/apps/blob/master/index.json).

**Comment by erickzhao** [comment]
Looking at the comparison, it seems like the 128px Abstract icon is the correct one so I'm not too sure about that https://github.com/erickzhao/apps/blob/master/apps/abstract/abstract-icon-128.png

**Comment by KrishJ999** [comment]
Oh, I had not checked the website before commenting!
I think that the issue has already been resolved.
This is the actual behaviour of the website with all the logos matching correctly with their respective software
[![Actual Behaviour.png](https://i.postimg.cc/G2SLSSYj/Screenshot-2022-10-06-084950.png)](https://postimg.cc/mzCWPjmc)
Hence, This issue should be closed.

**Comment by BlackHole1** [comment]
I just checked and the problem is still there. The problem manifests itself by first being normal and then becoming abnormal after a second.

https://user-images.githubusercontent.com/8198408/194683747-eecb8a94-7cab-4f5f-812a-6ee62b2fcb1d.mp4
