### ISSUE TITLE
Multiple "Tutorial" (on the same level) entries in the left navigation bar

### ISSUE THREAD

**Issue by albu77** [electron/electronjs.org-new#265]
ASAR Archives & Distributing Apps With Electron Forge are under their own Tutorial category which is at the same level that the First Tutorial Catégory just under Get Started
![image](https://user-images.githubusercontent.com/624802/193041777-e80ceb0e-bbe9-4f47-a874-377d2452a198.png)

**Comment by erickzhao** [comment]
@albu77 this is an issue with automation and requires some manual stitching. I'll try to change this ASAP.

**Comment by saichidvi** [comment]
@albu77  do you want , ASAR Archives & Distributing Apps With Electron Forge , should come under the first Tutorial ?

**Comment by saichidvi** [comment]
> @albu77 do you want , ASAR Archives & Distributing Apps With Electron Forge , should come under the first Tutorial ?

If this the problem , then assign it to me , I will fix the issue.

**Comment by erickzhao** [comment]
Fixed in https://github.com/electron/electronjs.org-new/pull/268
