### ISSUE TITLE
a mistake in the Chinese version of electron/docs/api/ipc-renderer.md

### ISSUE THREAD

**Issue by geraint23** [electron/electronjs.org-new#280]
See at [ipcRenderer.invoke(channel, ...args)](https://www.electronjs.org/zh/docs/latest/api/ipc-renderer#ipcrendererinvokechannel-args)
> 如果你不需要回复此消息，请考虑使用 ipcRender.sent

It is supposed to be `ipcRender.send`

**Comment by BlackHole1** [comment]
Thank you for your feedback! I fixed it now.
The site will be updated in about half an hour.
