### ISSUE TITLE
Nested lists not properly shown on new docs site

### ISSUE THREAD

**Issue by nornagon** [electron/electronjs.org-new#56]
e.g. https://www.electronjs.org/docs/latest/api/dialog/#dialogshowopendialogsyncbrowserwindow-options, the 'properties' list should be nested an extra level deep.

**Comment by erickzhao** [comment]
Seems like this has something to do with the `fixContent` function in our pre-build script.

https://github.com/electron/electronjs.org-new/blob/11a0f9d3f110cca54dacf63737c994612eabffa4/scripts/pre-build.js#L80

Commenting the above line out will restore proper list nesting in the markdown.
