### ISSUE TITLE
algolia search throws uncaught error on beta site 

### ISSUE THREAD

**Issue by ckerr** [electron/electronjs.org-new#60]
- load https://www.electronjs.org/docs/latest/
- click in the algolia textfield in upper-right corner to give focus
    - modal DocSearch dialog pops up
- type `ipcRenderer` into the `.docsearch_input` ('Search docs') input field
    - result: the DocSearch dialog has a spinning activity icon that never ends & gives no results

Network traffic while typing `ipcRenderer` gives all 404s:

Uncaught (in promise) 
{name: "ApiError", message: "Index beta-electronjs does not exist", status: 404, transporterStackTrace: Array(1)}

**Comment by erickzhao** [comment]
The index got disabled upstream, possibly because we changed the URLs around such that the base https://beta.electronjs.org URL doesn't work anymore.

We're on it!

**Comment by molant** [comment]
Search is working again!
