### ISSUE TITLE
Support multi-author blog posts

### ISSUE THREAD

**Issue by erickzhao** [electron/electronjs.org-new#93]
Following #92, blogs now support the multi-author format. We should either:

* Do pre-processing to transform the GitHub username format from the old website into one that the Docusaurus plugin accepts.
* [Swizzle](https://docusaurus.io/docs/using-themes#swizzling-theme-components) blog theme components so that the frontmatter automatically accepts our current format. (Note: swizzling during the beta phase is discouraged according to the docs because breaking changes might happen).

**Comment by molant** [comment]
I'm more inclined to do 1 TBH. IIRC I had to do some manual processing later to make sure Docusarus compiled everything correctly but it was just a few minutes.
Is the plan to migrate officially after this is implemented?

**Comment by molant** [comment]
Fixed via 6a8544a550d6ac28a49a2ea84cef643e704d4549
