### ISSUE TITLE
Show more levels in the documentation page table of contents

### ISSUE THREAD

**Issue by schontz** [electron/electronjs.org-new#99]
I couldn't find a feedback link on the new docs...

The table of contents links in the new docs leave much to be desired. A quick comparison:

Old docs:

![image](https://user-images.githubusercontent.com/2080286/132727653-aab1b64b-6ae6-403f-8243-bc03fe28dc65.png)

New docs:

![image](https://user-images.githubusercontent.com/2080286/132727711-41092e17-e2e2-44a3-921b-dedd88dbc5f0.png)

As you can see, the new docs omit all the actual events, properties, and methods. There is no way to see what is available without scrolling through pages and pages of content. And since [the headings and content run together](https://user-images.githubusercontent.com/2080286/132728232-5ac8d476-780c-4227-8518-b09184cc216a.png), it is quite hard to scan the page and determine what is available.

**Comment by erickzhao** [comment]
Hey @schontz, thanks for the report. We've moved it over to this repo.

I don't think Docusaurus has the ability to do this right now: https://github.com/facebook/docusaurus/issues/2700

**Comment by erickzhao** [comment]
I've opened https://github.com/facebook/docusaurus/pull/5578 to amend this :)

**Comment by erickzhao** [comment]
The upstream PR has been merged. We'll be picking up the additional configuration setting with Docusaurus 2.0.0-beta7
